### PR TITLE
remove black line on the bottom of the logo

### PR DESCRIPTION
**Pull request by luii**

### CODE REVIEW

**Comment by piranna** [comment]
Thank you :-) This one is an old version, but it's still used in several places :-)

**Comment by luii** [comment]
Ok i want to use this in the wiki and then i noticed this

**Comment by piranna** [comment]
SVG version is more recent and the preffered one. Didn't it work?

**Comment by luii** [comment]
Is the blue color of the svg correct?

**Comment by piranna** [comment]
> Is the blue color of the svg correct?

Yes it is, I adjusted it to be one of the basic VGA colors as is dictated
by NodeOS HIG so it can be prettily shown on terminals :-)

**Comment by luii** [comment]
okay that is cool :D

**Pull request merged**
